name: CI

on:
  push:
    branches:
      - master
  watch:
    types: [started]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository branch
      uses: actions/checkout@master
      with:
        ref: master
        fetch-depth: 1

    - name: Build
      uses: gcarreno/setup-lazarus@v3
      with:
        lazarus-version: "2.2.2"
        with-cache: true
      run: lazbuild -B "Cheat Engine/cheatengine.lpi" && lazbuild -B "Cheat Engine/speedhack/speedhack.lpr" && lazbuild -B "Cheat Engine/luaclient/luaclient.lpr" && lazbuild -B "Cheat Engine/VEHDebug/vehdebug.lpr"

    - name : Upload Artifact
      uses: actions/upload-artifact@master
      with:
        name: ALL
        path: "Cheat Engine"